version: '3.8'
services:
  chronos:
    build: .
    container_name: chronos_app
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
      - /app/node_modules
      - 'chronos_data:/app/data'
    environment:
      PORT: 3000
    restart: always
volumes:
  chronos_data: null
